### ISSUE TITLE
set default build mode for kernel modules to nodbg

### ISSUE THREAD

**Issue by FlorianRauh** [MEN-Mikro-Elektronik/13MD05-90#72]
Please set default build mode for kernel modules to >nodbg<
![mdsiwiz_default_nodbg](https://user-images.githubusercontent.com/40606803/52060462-8c2d8580-256c-11e9-8544-26780fcdcd0e.png)
This is also important for milestone 02.00 whereas it´s OK that all the tests were done with dbg modules only.

**Comment by mlassota** [comment]
Fixed

**Comment by FlorianRauh** [comment]
The GUI dialog solved the issue but
it´s not yet solved completly as the scan_system.sh produces a Makefile with "ALL_DBGS = dbg"
Please fix it.

**Comment by dpfeuffer** [comment]
Already specified as requirement in #84 MDIS Install and Scan Script Requirements.md.txt:
* scan_system.sh shall configure to build non-debug modules (ALL_DBGS = nodbg)

**Comment by KonradJPE** [comment]
Makefiles template option 'ALL_DBGS' is set to nodbg. 
mdiswiz default option is set to nodbg.
